spring.application.name=BootProj69-SpbRestProj09-APIDevelopment-MiniProject

#Datasource configuration
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=ravi
spring.datasource.password=system

#Hibernate JPA properties
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Embeded server port
#server.port=4041

#Context path
#server.servlet.context-path=/SpbRestProj10
